"use client";
import {useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
import {calculateScore,type Position} from "@/lib/scoring";

type ApiStat={apiPlayerId:number;name:string;club:string;competition:string;fixture:string;status:string;minutes:number;goals:number;assists:number;shotsOnTarget:number;bigChancesMissed:number;completedPasses:number;tacklesWon:number;penaltyGoals:number;penaltiesMissed:number;penaltiesConceded:number;saves:number;penaltiesSaved:number;goalsConceded:number;yellowCards:number;secondYellowCards:number;redCards:number;ownGoals:number;manOfTheMatch:boolean};
type RosterPlayer={id:number;full_name:string;position:string;club:string};
type Preview={date:string;requestsUsed:number;fixtures:Array<{id:number;competition:string;match:string;status:string}>;players:ApiStat[];limitations:string[]};
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/gi,"").toLowerCase();

export function ApiFootballTest({leagueId}:{leagueId:string}){
 const[data,setData]=useState<Preview|null>(null),[roster,setRoster]=useState<RosterPlayer[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function run(){setBusy(true);setMessage("");const{data:{session}}=await supabase.auth.getSession();if(!session){setMessage("Sign in again before running the test.");setBusy(false);return}const[picks,response]=await Promise.all([supabase.from("draft_picks").select("players(id,full_name,position,club)").eq("league_id",leagueId),fetch(`/api/football/today?league=${leagueId}`,{headers:{Authorization:`Bearer ${session.access_token}`}})]);const body=await response.json();if(!response.ok)setMessage(body.error??"The API test failed.");else{setData(body);setRoster((picks.data??[]).flatMap(item=>item.players?[item.players as unknown as RosterPlayer]:[]));setMessage(`Found ${body.fixtures.length} active or completed top-five-league matches.`)}setBusy(false)}
 const matches=useMemo(()=>{if(!data)return[];const rosterMap=new Map(roster.map(player=>[normalize(player.full_name),player]));return data.players.flatMap(stat=>{const player=rosterMap.get(normalize(stat.name));if(!player)return[];const score=calculateScore({position:player.position as Position,...stat});return[{player,stat,points:score.total,ledger:score.entries}]}) .sort((a,b)=>b.points-a.points)},[data,roster]);
 return <section className="panel commissioner-settings settings-form"><div className="section-row"><div><p className="eyebrow">API-FOOTBALL</p><h2>Real-stat scoring test</h2></div><span className="muted-chip">PREVIEW</span></div><p>Find players from this league’s drafted rosters who played today, then preview their scores without changing standings.</p><button type="button" className="primary-button full-button" disabled={busy} onClick={()=>void run()}>{busy?"Checking today’s matches…":"Find today’s roster players"}</button>{message?<p className="form-message">{message}</p>:null}{data?<><div className="settings-readonly"><span><strong>{data.date}</strong><small>{data.fixtures.length} matches · approximately {data.requestsUsed} of 100 daily API requests used</small></span><b>{matches.length} ROSTER PLAYERS</b></div>{matches.slice(0,12).map(({player,stat,points,ledger})=><article className="settings-readonly" key={`${stat.fixture}-${stat.apiPlayerId}`}><span><strong>{player.full_name} · {points} pts</strong><small>{stat.fixture} · {stat.minutes} min · {stat.goals} G · {stat.assists} A · {stat.shotsOnTarget} SOT</small><small>{ledger.map(item=>`${item.label} ${item.points>0?"+":""}${item.points}`).join(" · ")}</small></span><b>{stat.status.toUpperCase()}</b></article>)}{matches.length===0?<p>No drafted player could be matched to today’s API statistics.</p>:null}<p>{data.limitations.join(" ")}</p></>:null}</section>
}
