"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";

type Status={connected:boolean;plan?:string;active?:boolean;expiresAt?:string|null;requestsToday?:number|null;dailyLimit?:number|null;error?:string};

export function ApiFootballTest({leagueId}:{leagueId:string}){
 const[status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[scoreBusy,setScoreBusy]=useState(false),[nameBusy,setNameBusy]=useState(false),[injuryBusy,setInjuryBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void (async()=>{const token=await sessionToken();if(!token){setStatus({connected:false,error:"Sign in again."});return}void fetch("/api/football/status",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"}).then(response=>response.json()).then(setStatus).catch(()=>setStatus({connected:false,error:"Connection check failed"}))})()},[]);
 async function sessionToken(){const{data:{session}}=await supabase.auth.getSession();return session?.access_token??null}
 async function syncPlayers(){setBusy(true);setMessage("");try{const token=await sessionToken();if(!token){setMessage("Sign in again before synchronizing players.");return}const response=await fetch("/api/football/sync/players",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const body=await response.json().catch(()=>({error:"Player synchronization failed."}));const seasons=Object.values(body.seasonsUsed??{}) as number[];const seasonLabel=seasons.length?[...new Set(seasons)].sort((a,b)=>b-a).join(", "):"no available season";const unavailable=body.unavailable?.length?` No populated data was found for: ${body.unavailable.join(", ")}.`:"";setMessage(response.ok?`${body.imported} official API player profiles synchronized with headshots from season ${seasonLabel}; ${body.reconciled??0} existing fantasy players were linked to their official API identities using ${body.requestsUsed} API requests.${unavailable}`:body.error??"Player synchronization failed.")}catch{setMessage("Player synchronization failed. Please try again.")}finally{setBusy(false)}}
 async function syncNames(){setNameBusy(true);setMessage("");try{const token=await sessionToken();if(!token){setMessage("Sign in again before updating player names.");return}const response=await fetch("/api/football/sync/names",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const body=await response.json().catch(()=>({error:"Common-name update failed."}));setMessage(response.ok?`${body.updated} player names changed to their commonly used football names from ${body.playersFound} current API squad players using ${body.requestsUsed} requests. Rosters, rankings and scores were not changed.`:body.error??"Common-name update failed.")}catch{setMessage("Common-name update failed. Please try again.")}finally{setNameBusy(false)}}
 async function syncInjuries(){setInjuryBusy(true);setMessage("");try{const token=await sessionToken();if(!token){setMessage("Sign in again before synchronizing injuries.");return}const response=await fetch("/api/football/sync/injuries",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const body=await response.json().catch(()=>({error:"Injury synchronization failed."}));const unavailable=body.unavailable?.length?` Could not refresh: ${body.unavailable.join(", ")}.`:"";setMessage(response.ok?`${body.injuriesSynced??0} current injuries or suspensions synchronized across the Top Five leagues using ${body.requestsUsed??0} API requests. Return-date lookups: ${body.sidelinedLookups??0} new, ${body.sidelinedCacheHits??0} cached.${unavailable}`:body.error??"Injury synchronization failed.")}catch{setMessage("Injury synchronization failed. Please try again.")}finally{setInjuryBusy(false)}}
 async function syncScores(){setScoreBusy(true);setMessage("");try{const token=await sessionToken();if(!token){setMessage("Sign in again before synchronizing scores.");return}const response=await fetch("/api/football/sync/scores",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({leagueId})});const body=await response.json().catch(()=>({error:"Score synchronization failed."}));setMessage(response.ok?(body.message?`${body.message} Cached ${body.seasonFixturesCached??0} fixtures using ${body.requestsUsed} API requests.`:`${body.competition} ${body.round}: ${body.fixturesStarted} of ${body.fixturesTotal} matches started. Updated ${body.playersUpdated??body.lineupPlayersUpdated} fantasy players and cached ${body.seasonFixturesCached??body.fixturesTotal} season fixtures using ${body.requestsUsed} API requests. Open a player profile to see past and upcoming opponents.`):body.error??"Score synchronization failed.")}catch{setMessage("Score synchronization failed. Please try again.")}finally{setScoreBusy(false)}}
 const controlsBusy=busy||scoreBusy||nameBusy||injuryBusy;
 return <section className="panel commissioner-settings settings-form"><div className="section-row"><div><p className="eyebrow">API-FOOTBALL</p><h2>Synchronization controls</h2></div><span className="muted-chip">{status?.connected?`${status.plan?.toUpperCase()??"ACTIVE"} PLAN`:"CHECKING"}</span></div><p>Developer-only controls for current squads, common names, injuries, suspensions, headshots, fixtures and match statistics.</p>{status?<div className="settings-readonly"><span><strong>{status.connected&&status.active?"Connected and active":"Connection needs attention"}</strong><small>{status.connected?`${status.requestsToday??0} of ${status.dailyLimit??"—"} requests used today${status.expiresAt?` · active through ${new Date(status.expiresAt).toLocaleDateString()}`:""}`:status.error}</small></span><b>{status.connected?"LIVE":"OFFLINE"}</b></div>:null}<button type="button" className="primary-button full-button" disabled={controlsBusy||!status?.connected||!leagueId} onClick={()=>void syncScores()}>{scoreBusy?"Calculating current matchweek…":"Sync selected league scores"}</button><button type="button" className="secondary-button full-button" disabled={controlsBusy||!status?.connected} onClick={()=>void syncInjuries()}>{injuryBusy?"Synchronizing injuries and suspensions…":"Sync injuries and suspensions"}</button><button type="button" className="secondary-button full-button" disabled={controlsBusy||!status?.connected} onClick={()=>void syncNames()}>{nameBusy?"Applying common player names…":"Sync common player names"}</button><button type="button" className="secondary-button full-button" disabled={controlsBusy||!status?.connected} onClick={()=>void syncPlayers()}>{busy?"Synchronizing Top Five players…":"Sync current squads and headshots"}</button>{message?<p className="form-message">{message}</p>:null}<p className="settings-note">Injury and player/name syncs update the global pool. Score sync follows the selected league’s season-locked Fantasy Calendar.</p></section>
}
