"use client";
import{useCallback,useEffect,useState}from"react";
import{supabase}from"@/lib/supabase";

type Lock={gameweek:number;locked_at:string;correction_expires_at:string|null;correction_reason:string|null};

export function FinalizedGameweekControls({leagueId}:{leagueId:string}){
 const[locks,setLocks]=useState<Lock[]>([]),[gameweek,setGameweek]=useState(1),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!leagueId){setLocks([]);return}const{data:{session}}=await supabase.auth.getSession();if(!session)return;const response=await fetch(`/api/developer/finalized-gameweeks?leagueId=${encodeURIComponent(leagueId)}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const body=await response.json().catch(()=>({locks:[]}));if(response.ok){setLocks(body.locks??[]);setGameweek((body.locks??[])[0]?.gameweek??1)}},[leagueId]);
 useEffect(()=>{void load()},[load]);
 async function act(action:"unlock"|"relock"|"restore"){
  if(action==="restore"&&!window.confirm(`Restore Fantasy GW${gameweek} to its last locked snapshot? This replaces its historical scores, lineups, auto-subs, and matchups.`))return;
  setBusy(true);setMessage("");
  try{const{data:{session}}=await supabase.auth.getSession();if(!session){setMessage("Sign in again.");return}const response=await fetch("/api/developer/finalized-gameweeks",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({leagueId,gameweek,action,reason})});const body=await response.json().catch(()=>({error:"Action failed."}));setMessage(response.ok?action==="unlock"?`GW${gameweek} correction window opened for 15 minutes. Cron remains blocked.`:action==="relock"?`GW${gameweek} snapshot updated and locked again.`:`GW${gameweek} restored to its locked snapshot.`:body.error??"Action failed.");if(response.ok){setReason("");await load()}}finally{setBusy(false)}
 }
 const selected=locks.find(lock=>lock.gameweek===gameweek),open=Boolean(selected?.correction_expires_at&&new Date(selected.correction_expires_at)>new Date());
 return <section className="panel settings-form"><div className="section-row"><div><p className="eyebrow">FINALIZED WEEK PROTECTION</p><h2>Immutable gameweek snapshots</h2></div><span className="muted-chip">{open?"CORRECTION OPEN":"LOCKED"}</span></div><p>Wrapped gameweeks reject score, matchup, lineup, and auto-sub writes. Only your developer account can open a 15-minute correction window; every action is audited.</p>{locks.length?<><label className="settings-field"><span><strong>Finalized gameweek</strong><small>{selected?`Locked ${new Date(selected.locked_at).toLocaleString()}`:"Select a snapshot"}</small></span><select value={gameweek} onChange={event=>setGameweek(Number(event.target.value))}>{locks.map(lock=><option key={lock.gameweek} value={lock.gameweek}>Gameweek {lock.gameweek}</option>)}</select></label><label className="settings-field"><span><strong>Correction reason</strong><small>Required to open or restore a finalized week.</small></span><input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Describe exactly what must be corrected"/></label>{open?<button className="primary-button full-button" disabled={busy} onClick={()=>void act("relock")}>Save snapshot and relock now</button>:<button className="secondary-button full-button" disabled={busy||reason.trim().length<10} onClick={()=>void act("unlock")}>Open 15-minute correction window</button>}<button className="secondary-button full-button" disabled={busy||reason.trim().length<10} onClick={()=>void act("restore")}>Restore last locked snapshot</button></>:<p className="form-message">No finalized gameweek snapshots exist yet.</p>}{message?<p className="form-message">{message}</p>:null}<p className="settings-note">A correction window never unlocks cron jobs. If no action is taken, it expires automatically and the snapshot stays locked.</p></section>
}
