"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AccountMenu } from "./account-menu";
import { BottomNav } from "./bottom-nav";
import { resolveActiveLeague } from "@/lib/active-league";
import { supabase } from "@/lib/supabase";

type League={league_id:string;league_name:string;league_size:number;manager_count:number;team_name:string;game_format:string};
type Draft={status:"waiting"|"live"|"paused"|"complete";current_pick:number;pick_deadline:string|null};
type Manager={draft_slot:number;user_id:string;team_name:string};
type Pick={id:number;pick_number:number;user_id:string;auto_picked:boolean;players?:{full_name:string;position:string;club:string}|null};
type Matchup={id:string;gameweek:number;home_user_id:string;away_user_id:string;home_score:number|string;away_score:number|string;status:"scheduled"|"live"|"final"};
type Standing={rank:number;user_id:string;team_name:string;wins:number;draws:number;losses:number;points:number};
type WindowState={gameweek:number;phase:string};

function managerAtPick(order:Manager[],pickNumber:number){if(!order.length)return undefined;const round=Math.floor((pickNumber-1)/order.length)+1,index=(pickNumber-1)%order.length,slot=round%2?index+1:order.length-index;return order.find(manager=>manager.draft_slot===slot)}

export function HomeDashboard(){
  const[league,setLeague]=useState<League|null>(null),[draft,setDraft]=useState<Draft|null>(null),[order,setOrder]=useState<Manager[]>([]),[picks,setPicks]=useState<Pick[]>([]),[matchup,setMatchup]=useState<Matchup|null>(null),[standings,setStandings]=useState<Standing[]>([]),[windowState,setWindowState]=useState<WindowState|null>(null);
  const[lineupCount,setLineupCount]=useState(0),[hasCaptain,setHasCaptain]=useState(false),[rosterCount,setRosterCount]=useState(0),[unreadTrades,setUnreadTrades]=useState(0);
  const[userId,setUserId]=useState<string|null>(null),[name,setName]=useState("Manager"),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(true),[now,setNow]=useState(Date.now());

  const load=useCallback(async()=>{
    const{data:{user}}=await supabase.auth.getUser();if(!user){setSignedIn(false);setLoading(false);return}setUserId(user.id);setName(String(user.user_metadata?.display_name??user.email?.split("@")[0]??"Manager"));
    const{data:leagueData}=await supabase.rpc("my_leagues");const active=resolveActiveLeague((leagueData??[]) as League[],new URLSearchParams(window.location.search).get("league"))??null;setLeague(active);if(!active){setLoading(false);return}
    const[d,o,p,t,l,c,w,s,m]=await Promise.all([
      supabase.from("drafts").select("status,current_pick,pick_deadline").eq("league_id",active.league_id).maybeSingle(),supabase.rpc("draft_order",{p_league_id:active.league_id}),supabase.from("draft_picks").select("id,pick_number,user_id,auto_picked,players(full_name,position,club)").eq("league_id",active.league_id).order("pick_number",{ascending:false}),supabase.rpc("unread_trade_count",{p_league_id:active.league_id}),supabase.from("lineup_players").select("is_starter,is_captain").eq("league_id",active.league_id).eq("user_id",user.id),supabase.from("pack_cards").select("id",{count:"exact",head:true}).eq("league_id",active.league_id).eq("user_id",user.id).not("active_slot","is",null),supabase.rpc("transaction_window",{p_league_id:active.league_id}),supabase.rpc("league_standings",{p_league_id:active.league_id}),supabase.from("league_matchups").select("id,gameweek,home_user_id,away_user_id,home_score,away_score,status").eq("league_id",active.league_id).or(`home_user_id.eq.${user.id},away_user_id.eq.${user.id}`).order("gameweek",{ascending:false})]);
    const pickData=(p.data??[]) as unknown as Pick[],lineup=(l.data??[]) as {is_starter:boolean;is_captain:boolean}[],matches=(m.data??[]) as Matchup[],transactionWindow=((w.data??[])[0] as WindowState|undefined)??null;setDraft((d.data as Draft|null)??null);setOrder((o.data??[]) as Manager[]);setPicks(pickData);setUnreadTrades(Number(t.data??0));setLineupCount(lineup.filter(row=>row.is_starter).length);setHasCaptain(lineup.some(row=>row.is_captain));setRosterCount(active.game_format==="pack"?Number(c.count??0):pickData.filter(row=>row.user_id===user.id).length);setWindowState(transactionWindow);setStandings((s.data??[]) as Standing[]);setMatchup(matches.find(x=>x.status==="live")??matches.find(x=>x.status==="scheduled")??matches[0]??null);setLoading(false)
  },[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[load]);
  useEffect(()=>{if(!league)return;const channel=supabase.channel(`home:${league.league_id}`).on("postgres_changes",{event:"*",schema:"public",table:"drafts",filter:`league_id=eq.${league.league_id}`},()=>void load()).on("postgres_changes",{event:"INSERT",schema:"public",table:"draft_picks",filter:`league_id=eq.${league.league_id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"league_matchups",filter:`league_id=eq.${league.league_id}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[league,load]);

  const current=draft?managerAtPick(order,draft.current_pick):undefined,isMyTurn=draft?.status==="live"&&current?.user_id===userId,seconds=draft?.pick_deadline?Math.max(0,Math.ceil((new Date(draft.pick_deadline).getTime()-now)/1000)):0,totalPicks=Math.max(1,order.length*18),progress=draft?Math.min(100,((draft.current_pick-1)/totalPicks)*100):0;
  const opponentId=matchup?(matchup.home_user_id===userId?matchup.away_user_id:matchup.home_user_id):null,opponent=order.find(x=>x.user_id===opponentId)?.team_name??"Opponent",myScore=matchup?Number(matchup.home_user_id===userId?matchup.home_score:matchup.away_score):0,opponentScore=matchup?Number(matchup.home_user_id===userId?matchup.away_score:matchup.home_score):0,myStanding=standings.find(x=>x.user_id===userId),lineupReady=lineupCount===11&&hasCaptain,draftReady=draft?.status==="complete"||league?.game_format==="pack";
  const action=useMemo(()=>{if(!league)return null;if(draft?.status==="live")return{eyebrow:isMyTurn?"YOUR TURN":"LIVE DRAFT",title:isMyTurn?"You’re on the clock.":`${current?.team_name??"A manager"} is picking.`,copy:isMyTurn?"Your queue is ready. Make the next selection before time expires.":`Pick ${draft.current_pick} of ${totalPicks} is underway.`,href:`/draft?league=${league.league_id}`,label:isMyTurn?"Make my pick":"Enter draft room"};if(league.game_format==="pack"&&rosterCount===0)return{eyebrow:"WELCOME PACK",title:"Build your first squad.",copy:"Open your starter bundle and reveal your captain, superstar and regular players.",href:`/packs?league=${league.league_id}`,label:"Open my packs"};if(draftReady&&!lineupReady)return{eyebrow:"LINEUP NEEDED",title:"Finish your Starting XI.",copy:`${lineupCount}/11 starters selected${hasCaptain?"":" · captain still needed"}.`,href:`/team?league=${league.league_id}`,label:"Set my lineup"};if(unreadTrades)return{eyebrow:"NEW TRADE OFFER",title:`${unreadTrades} offer${unreadTrades===1?" is":"s are"} waiting.`,copy:"Review, accept, decline or send a counteroffer.",href:`/trades?league=${league.league_id}`,label:"Review trades"};if(matchup)return{eyebrow:`GAMEWEEK ${matchup.gameweek}`,title:matchup.status==="live"?"Your matchup is live.":matchup.status==="final"?"Your result is ready.":`Next up: ${opponent}`,copy:matchup.status==="scheduled"?"Your saved Starting XI will score when the matchweek begins.":"Open the matchup for live player totals and scoring breakdowns.",href:`/matchup?league=${league.league_id}`,label:"Open matchup"};return{eyebrow:"LEAGUE READY",title:"Your season command center.",copy:"Set your lineup, watch the market and prepare for the next matchweek.",href:`/team?league=${league.league_id}`,label:"Open my team"}},[current?.team_name,draft?.current_pick,draft?.status,draftReady,hasCaptain,isMyTurn,league,lineupCount,lineupReady,matchup,opponent,rosterCount,totalPicks,unreadTrades]);

  return <main className="app-shell home-dashboard"><header className="topbar home-topbar"><div><p className="eyebrow">{league?.league_name??"XI FANTASY"}</p><h1>{loading?"Loading dashboard…":`Welcome, ${name}`}</h1>{league?<small>{league.team_name}</small>:null}</div><AccountMenu/></header>
    {!loading&&!signedIn?<section className="match-card home-empty"><p className="eyebrow">YOUR SEASON</p><h2>Sign in to open your dashboard.</h2><p>Your leagues, lineup and matchup will appear here.</p><Link className="primary-button" href="/login?next=/">Log in</Link></section>:null}
    {!loading&&signedIn&&!league?<section className="match-card home-empty"><p className="eyebrow">START HERE</p><h2>Create or join your first league.</h2><p>Once you join, Home becomes your season command center.</p><Link className="primary-button" href="/league">Open leagues</Link></section>:null}
    {league&&action?<section className={`match-card home-command-card ${isMyTurn?"my-turn":""}`}><div className="home-command-head"><div><p className="eyebrow">{action.eyebrow}</p><h2>{action.title}</h2></div>{draft?.status==="live"?<span className="live-pill"><span/>LIVE</span>:matchup?<span className={`home-status ${matchup.status}`}>{matchup.status}</span>:null}</div><p>{action.copy}</p>{draft?.status==="live"?<><div className="home-clock"><strong>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</strong><small>Pick {draft.current_pick} of {totalPicks}</small></div><div className="progress"><span style={{width:`${progress}%`}}/></div></>:null}<Link className="primary-button home-primary-link" href={action.href}>{action.label} →</Link></section>:null}
    {league&&matchup?<section className="panel home-matchup-card"><div className="section-row"><div><p className="eyebrow">GAMEWEEK {matchup.gameweek}</p><h2>{matchup.status==="final"?"Final score":"Head to head"}</h2></div><span className={`home-status ${matchup.status}`}>{matchup.status}</span></div><div className="home-scoreboard"><div className="home-score-team mine"><span>{league.team_name}</span><strong>{myScore}</strong></div><b>VS</b><div className="home-score-team"><span>{opponent}</span><strong>{opponentScore}</strong></div></div><Link className="home-card-link" href={`/matchup?league=${league.league_id}`}>View matchup and player scores <span>→</span></Link></section>:null}
    {league?<><section className="home-season-strip"><div><span>RANK</span><strong>{myStanding?`#${myStanding.rank}`:"—"}</strong></div><div><span>RECORD</span><strong>{myStanding?`${myStanding.wins}-${myStanding.draws}-${myStanding.losses}`:"0-0-0"}</strong></div><div><span>LINEUP</span><strong className={lineupReady?"ready":"attention"}>{lineupReady?"READY":`${lineupCount}/11`}</strong></div></section>
      <section className="home-section"><div className="section-row"><div><p className="eyebrow">MANAGE</p><h2>League actions</h2></div></div><div className="home-action-grid"><Link href={`/team?league=${league.league_id}`}><span>◎</span><div><strong>My Team</strong><small>{lineupReady?"Lineup & captain ready":"Action required"}</small></div>{!lineupReady&&draftReady?<b className="home-action-alert">!</b>:null}</Link><Link href={`/players?league=${league.league_id}`}><span>⌕</span><div><strong>Players</strong><small>{league.game_format==="pack"?"Collection & market":"Free agents & stats"}</small></div></Link><Link href={league.game_format==="pack"?`/packs?league=${league.league_id}#auction`:`/waivers?league=${league.league_id}`}><span>↻</span><div><strong>{league.game_format==="pack"?"Auction":"Waivers"}</strong><small>{league.game_format==="pack"?"League card market":windowState?`GW ${windowState.gameweek} · ${windowState.phase.replace("_"," ")}`:"Claims & priority"}</small></div></Link><Link href={`/trades?league=${league.league_id}`}><span>⇄</span><div><strong>Trades</strong><small>{unreadTrades?`${unreadTrades} new offer${unreadTrades===1?"":"s"}`:"Offers & history"}</small></div>{unreadTrades?<b className="home-action-alert red">{unreadTrades}</b>:null}</Link></div></section>
      <section className="panel home-table-card"><div className="section-row"><div><p className="eyebrow">STANDINGS</p><h2>League table</h2></div><Link className="text-button" href={`/matchup?league=${league.league_id}`}>Full table</Link></div><div className="home-table-head"><span>#</span><span>Club</span><span>W-D-L</span><span>Pts</span></div>{standings.slice(0,5).map(row=><div className={`home-table-row ${row.user_id===userId?"mine":""}`} key={row.user_id}><span>{row.rank}</span><strong>{row.team_name}</strong><span>{row.wins}-{row.draws}-{row.losses}</span><b>{row.points}</b></div>)}{!standings.length?<p className="empty-state">Standings begin after the first matchup.</p>:null}</section>
      <section className="panel home-roster"><div className="section-row"><div><p className="eyebrow">MY CLUB</p><h2>{league.team_name}</h2></div><Link className="text-button" href={`/team?league=${league.league_id}`}>Open team</Link></div><div className="home-roster-progress"><strong>{rosterCount}<small>/18</small></strong><span><b>{lineupReady?"Starting XI ready":"Lineup needs attention"}</b><small>{hasCaptain?"Captain selected":"Choose your captain"}</small></span></div><div className="progress"><span style={{width:`${Math.min(100,(rosterCount/18)*100)}%`}}/></div></section>
      {draft?.status!=="complete"&&picks.length?<section className="panel home-activity"><div className="section-row"><div><p className="eyebrow">LEAGUE ACTIVITY</p><h2>Recent picks</h2></div><Link className="text-button" href={`/draft?league=${league.league_id}`}>Draft room</Link></div>{picks.slice(0,4).map(pick=><div className="home-pick-row" key={pick.id}><b>#{pick.pick_number}</b><span><strong>{pick.players?.full_name??"Player"}</strong><small>{order.find(manager=>manager.user_id===pick.user_id)?.team_name??"Manager"}</small></span>{pick.auto_picked?<em>AUTO</em>:null}</div>)}</section>:null}</>:null}<BottomNav/></main>;
}
