"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
import {calculateScore,type Position} from "@/lib/scoring";

type Player={id:number;full_name:string;position:string;club:string;competition?:string;photo_url?:string|null};
type ScoreRow={gameweek:number;rating:number|null;minutes:number;goals:number;assists:number;shots_on_target:number;big_chances_missed:number;completed_passes:number;tackles_won:number;penalty_goals:number;penalties_missed:number;penalties_conceded:number;saves:number;penalties_saved:number;goals_conceded:number;yellow_cards:number;second_yellow_cards:number;red_cards:number;own_goals:number;man_of_the_match:boolean;status:string};
type Fixture={fixture_id:number;gameweek:number;kickoff:string;status:string;home_team:string;away_team:string;home_score:number|null;away_score:number|null};

const clubAliases:Record<string,string[]>={"psg":["paris saint germain"],"bayern munich":["bayern munchen","bayern münchen"],"inter milan":["inter"],"ac milan":["milan"],"athletic bilbao":["athletic club"],"real betis":["betis"]};
function teamKey(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\b(fc|cf|ac)\b/g,"").replace(/[^a-z0-9]/g,"")}
function isPlayersClub(team:string,club:string){const teamName=teamKey(team),clubName=teamKey(club);return teamName===clubName||(clubAliases[club.toLowerCase()]??[]).some(alias=>teamName===teamKey(alias))}
function opponent(fixture:Fixture,club:string){return isPlayersClub(fixture.home_team,club)?fixture.away_team:fixture.home_team}
function result(fixture:Fixture,club:string){if(fixture.home_score===null||fixture.away_score===null)return null;const home=isPlayersClub(fixture.home_team,club);return `${home?fixture.home_score:fixture.away_score}-${home?fixture.away_score:fixture.home_score}`}

export function PlayerStatsDialog({leagueId,player,onClose}:{leagueId:string;player:Player;onClose:()=>void}){
  const[scores,setScores]=useState<ScoreRow[]>([]),[fixtures,setFixtures]=useState<Fixture[]>([]),[loading,setLoading]=useState(true);
  useEffect(()=>{void(async()=>{const[scoreResult,fixtureResult]=await Promise.all([supabase.from("league_player_scores").select("gameweek,rating,minutes,goals,assists,shots_on_target,big_chances_missed,completed_passes,tackles_won,penalty_goals,penalties_missed,penalties_conceded,saves,penalties_saved,goals_conceded,yellow_cards,second_yellow_cards,red_cards,own_goals,man_of_the_match,status").eq("league_id",leagueId).eq("player_id",player.id).order("gameweek",{ascending:false}),supabase.from("league_headline_fixtures").select("fixture_id,gameweek,kickoff,status,home_team,away_team,home_score,away_score").eq("league_id",leagueId).order("kickoff",{ascending:true})]);setScores((scoreResult.data??[]) as ScoreRow[]);setFixtures(((fixtureResult.data??[]) as Fixture[]).filter(fixture=>isPlayersClub(fixture.home_team,player.club)||isPlayersClub(fixture.away_team,player.club)));setLoading(false)})()},[leagueId,player.id,player.club]);
  const totals=useMemo(()=>scores.reduce((all,row)=>{const points=calculateScore({position:player.position as Position,minutes:row.minutes,goals:row.goals,assists:row.assists,shotsOnTarget:row.shots_on_target,completedPasses:row.completed_passes,tacklesWon:row.tackles_won,penaltyGoals:row.penalty_goals,penaltiesMissed:row.penalties_missed,penaltiesConceded:row.penalties_conceded,saves:row.saves,penaltiesSaved:row.penalties_saved,goalsConceded:row.goals_conceded,yellowCards:row.yellow_cards,secondYellowCards:row.second_yellow_cards,redCards:row.red_cards,ownGoals:row.own_goals,manOfTheMatch:row.man_of_the_match}).total;all.points+=points;all.appearances+=row.minutes>0?1:0;all.minutes+=row.minutes;all.goals+=row.goals;all.assists+=row.assists;all.shotsOnTarget+=row.shots_on_target;all.tacklesWon+=row.tackles_won;all.completedPasses+=row.completed_passes;all.saves+=row.saves;all.cleanSheets+=row.minutes>=60&&row.goals_conceded===0&&(player.position==="GK"||player.position==="DEF")?1:0;all.gameweeks.push({gameweek:row.gameweek,points,status:row.status,rating:row.rating,manOfTheMatch:row.man_of_the_match});return all},{points:0,appearances:0,minutes:0,goals:0,assists:0,shotsOnTarget:0,tacklesWon:0,completedPasses:0,saves:0,cleanSheets:0,gameweeks:[]} as {points:number;appearances:number;minutes:number;goals:number;assists:number;shotsOnTarget:number;tacklesWon:number;completedPasses:number;saves:number;cleanSheets:number;gameweeks:Array<{gameweek:number;points:number;status:string;rating:number|null;manOfTheMatch:boolean}>}),[scores,player.position]);
  const fixtureByWeek=new Map(fixtures.map(fixture=>[fixture.gameweek,fixture])),completed=new Set(["FT","AET","PEN"]),now=Date.now();
  const nextFixture=fixtures.find(fixture=>!completed.has(fixture.status)&&new Date(fixture.kickoff).getTime()>=now-3*60*60*1000)??null;
  const hasCompletedFixture=fixtures.some(fixture=>completed.has(fixture.status)&&new Date(fixture.kickoff).getTime()<now);
  const venue=(fixture:Fixture)=>isPlayersClub(fixture.home_team,player.club)?"Home":"Away";
  return <div className="waiver-overlay stats-overlay" role="dialog" aria-modal="true" aria-label={`${player.full_name} statistics`} onClick={onClose}><section className="panel player-stats-dialog" onClick={event=>event.stopPropagation()}><button className="stats-close" onClick={onClose} aria-label="Close player statistics">×</button>{player.photo_url?<img className="player-profile-headshot" src={player.photo_url} alt={`${player.full_name} headshot`} onError={event=>{event.currentTarget.style.display="none"}}/>:null}<p className="eyebrow">PLAYER PROFILE</p><h2>{player.full_name}</h2><p>{player.position} · {player.club}{player.competition?` · ${player.competition}`:""}</p><div className="player-next-match"><small>NEXT MATCH</small>{nextFixture?<><strong>vs {opponent(nextFixture,player.club)}</strong><span>{venue(nextFixture)} · {new Date(nextFixture.kickoff).toLocaleString([], {weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})} · GW {nextFixture.gameweek}</span></>:<><strong>Fixture to be confirmed</strong><span>The next API fixture has not been synchronized yet.</span></>}</div><div className="stats-hero"><strong>{totals.points}</strong><span>FANTASY POINTS</span></div><div className="stats-grid"><div><b>{totals.appearances}</b><small>Apps</small></div><div><b>{totals.minutes}</b><small>Minutes</small></div><div><b>{totals.goals}</b><small>Goals</small></div><div><b>{totals.assists}</b><small>Assists</small></div><div><b>{totals.shotsOnTarget}</b><small>Shots on target</small></div><div><b>{totals.tacklesWon}</b><small>Tackles won</small></div><div><b>{totals.completedPasses}</b><small>Passes</small></div><div><b>{player.position==="GK"?totals.saves:totals.cleanSheets}</b><small>{player.position==="GK"?"Saves":"Clean sheets"}</small></div></div><div className="gameweek-stats"><h3>Gameweek performance</h3>{loading?<p>Loading statistics…</p>:totals.gameweeks.length?totals.gameweeks.map(week=>{const fixture=fixtureByWeek.get(week.gameweek);return <div key={week.gameweek}><span><b>GW {week.gameweek}</b>{fixture?<small>vs {opponent(fixture,player.club)}{result(fixture,player.club)?` · ${result(fixture,player.club)}`:""}</small>:<small>Opponent unavailable</small>}</span><small>{week.status.replace("_"," ")}</small><span className="gameweek-score-summary"><span className="match-rating">{week.rating!==null?week.rating.toFixed(1):"—"}{week.manOfTheMatch?<img src="/motm-badge.png" alt="Man of the Match" title="Man of the Match"/>:null}</span><b>{week.points} FP</b></span></div>}):<p>No match statistics have been recorded yet.</p>}</div>{!loading&&!hasCompletedFixture?<p className="season-status-note">* Season not started. No previous match has been recorded for {player.club}.</p>:null}</section></div>;
}
