"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
import {calculateScore,type Position} from "@/lib/scoring";

type Player={id:number;full_name:string;position:string;club:string;competition?:string};
type ScoreRow={gameweek:number;minutes:number;goals:number;assists:number;shots_on_target:number;big_chances_missed:number;completed_passes:number;tackles_won:number;penalty_goals:number;penalties_missed:number;penalties_conceded:number;saves:number;penalties_saved:number;goals_conceded:number;yellow_cards:number;second_yellow_cards:number;red_cards:number;own_goals:number;man_of_the_match:boolean;status:string};

export function PlayerStatsDialog({leagueId,player,onClose}:{leagueId:string;player:Player;onClose:()=>void}){
  const[scores,setScores]=useState<ScoreRow[]>([]),[loading,setLoading]=useState(true);
  useEffect(()=>{void(async()=>{const{data}=await supabase.from("league_player_scores").select("gameweek,minutes,goals,assists,shots_on_target,big_chances_missed,completed_passes,tackles_won,penalty_goals,penalties_missed,penalties_conceded,saves,penalties_saved,goals_conceded,yellow_cards,second_yellow_cards,red_cards,own_goals,man_of_the_match,status").eq("league_id",leagueId).eq("player_id",player.id).order("gameweek",{ascending:false});setScores((data??[]) as ScoreRow[]);setLoading(false)})()},[leagueId,player.id]);
  const totals=useMemo(()=>scores.reduce((all,row)=>{const points=calculateScore({position:player.position as Position,minutes:row.minutes,goals:row.goals,assists:row.assists,shotsOnTarget:row.shots_on_target,bigChancesMissed:row.big_chances_missed,completedPasses:row.completed_passes,tacklesWon:row.tackles_won,penaltyGoals:row.penalty_goals,penaltiesMissed:row.penalties_missed,penaltiesConceded:row.penalties_conceded,saves:row.saves,penaltiesSaved:row.penalties_saved,goalsConceded:row.goals_conceded,yellowCards:row.yellow_cards,secondYellowCards:row.second_yellow_cards,redCards:row.red_cards,ownGoals:row.own_goals,manOfTheMatch:row.man_of_the_match}).total;all.points+=points;all.appearances+=row.minutes>0?1:0;all.minutes+=row.minutes;all.goals+=row.goals;all.assists+=row.assists;all.shotsOnTarget+=row.shots_on_target;all.tacklesWon+=row.tackles_won;all.completedPasses+=row.completed_passes;all.saves+=row.saves;all.cleanSheets+=row.minutes>=60&&row.goals_conceded===0&&(player.position==="GK"||player.position==="DEF")?1:0;all.gameweeks.push({gameweek:row.gameweek,points,status:row.status});return all},{points:0,appearances:0,minutes:0,goals:0,assists:0,shotsOnTarget:0,tacklesWon:0,completedPasses:0,saves:0,cleanSheets:0,gameweeks:[]} as {points:number;appearances:number;minutes:number;goals:number;assists:number;shotsOnTarget:number;tacklesWon:number;completedPasses:number;saves:number;cleanSheets:number;gameweeks:Array<{gameweek:number;points:number;status:string}>}),[scores,player.position]);
  return <div className="waiver-overlay stats-overlay" role="dialog" aria-modal="true" aria-label={`${player.full_name} statistics`} onClick={onClose}><section className="panel player-stats-dialog" onClick={event=>event.stopPropagation()}><button className="stats-close" onClick={onClose} aria-label="Close player statistics">×</button><p className="eyebrow">PLAYER PROFILE</p><h2>{player.full_name}</h2><p>{player.position} · {player.club}{player.competition?` · ${player.competition}`:""}</p><div className="stats-hero"><strong>{totals.points}</strong><span>FANTASY POINTS</span></div><div className="stats-grid"><div><b>{totals.appearances}</b><small>Apps</small></div><div><b>{totals.minutes}</b><small>Minutes</small></div><div><b>{totals.goals}</b><small>Goals</small></div><div><b>{totals.assists}</b><small>Assists</small></div><div><b>{totals.shotsOnTarget}</b><small>Shots on target</small></div><div><b>{totals.tacklesWon}</b><small>Tackles won</small></div><div><b>{totals.completedPasses}</b><small>Passes</small></div><div><b>{player.position==="GK"?totals.saves:totals.cleanSheets}</b><small>{player.position==="GK"?"Saves":"Clean sheets"}</small></div></div><div className="gameweek-stats"><h3>Gameweek points</h3>{loading?<p>Loading statistics…</p>:totals.gameweeks.length?totals.gameweeks.map(week=><div key={week.gameweek}><span>GW {week.gameweek}</span><small>{week.status.replace("_"," ")}</small><b>{week.points} FP</b></div>):<p>No match statistics have been recorded yet.</p>}</div></section></div>;
}
