"use client";

import { useCallback, useEffect, useState } from "react";
import {supabase} from "@/lib/supabase";
import type {LabMatch,LabMatchDetails} from "@/lib/fotmob-provider-lab";

async function token(){const{data:{session}}=await supabase.auth.getSession();return session?.access_token??null}
async function labFetch(path:string){const access=await token();if(!access)throw new Error("Sign in again.");const response=await fetch(path,{headers:{Authorization:`Bearer ${access}`},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Provider test failed.");return body}

export function ProviderLab(){
 const[date,setDate]=useState(new Date().toISOString().slice(0,10)),[matches,setMatches]=useState<LabMatch[]>([]),[selected,setSelected]=useState<LabMatchDetails|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const loadMatches=useCallback(async()=>{setBusy(true);setMessage("");setSelected(null);try{const body=await labFetch(`/api/provider-lab?mode=matches&date=${date.replaceAll("-","")}`);setMatches(body.matches??[]);setMessage(`${body.matches?.length??0} matches found. The upstream response is shared for five minutes.`)}catch(error){setMessage(error instanceof Error?error.message:"Match lookup failed.")}finally{setBusy(false)}},[date]);
 async function loadMatch(matchId:number){setBusy(true);setMessage("");try{const body=await labFetch(`/api/provider-lab?mode=match&matchId=${matchId}`);setSelected(body);setMessage(`Calculated ${body.players?.length??0} player scores from the cached FotMob match payload. Nothing was written to Supabase.`)}catch(error){setMessage(error instanceof Error?error.message:"Match-stat lookup failed.")}finally{setBusy(false)}}
 useEffect(()=>{void loadMatches()},[loadMatches]);
 return <><section className="panel settings-form"><div className="section-row"><div><p className="eyebrow">ISOLATED PREVIEW</p><h2>Provider Lab</h2></div><span className="muted-chip">NO DATABASE WRITES</span></div><p>Choose a date and open a match to calculate fantasy points from FotMob data with the production scoring rules. Upstream responses are cached for five minutes.</p><label className="settings-field"><span><strong>Match date</strong><small>Loads the public match list for this date.</small></span><input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button className="primary-button full-button" disabled={busy} onClick={()=>void loadMatches()}>{busy?"Loading provider data…":"Load matches"}</button>{message?<p className="form-message">{message}</p>:null}</section><section className="panel"><div className="section-row"><div><p className="eyebrow">MATCH FEED</p><h2>{matches.length} matches</h2></div></div><div className="settings-readonly-list">{matches.map(match=><div key={match.id}><span><strong>{match.home} vs {match.away}</strong><small>{match.league} · {match.kickoff} · {match.finished?"Final":match.started?"Live":"Scheduled"}</small></span><button className="secondary-button" disabled={busy} onClick={()=>void loadMatch(match.id)}>{match.score} · Test</button></div>)}</div></section>{selected?<section className="panel"><div className="section-row"><div><p className="eyebrow">ISOLATED CALCULATOR</p><h2>{selected.home} {selected.score} {selected.away}</h2></div><span className="muted-chip">{selected.status.toUpperCase()}</span></div><p className="settings-note">Covered in this read-only test: minutes, goals, assists, passes, shots on target, tackles, saves, goals conceded, cards, penalties and own goals.</p><div className="settings-readonly-list">{selected.players.map(player=><div key={player.fotmobId}><span><strong>{player.name} · {player.position}</strong><small>{player.team} · {player.stats.minutes} min · {player.stats.goals??0} G · {player.stats.assists??0} A · {player.stats.completedPasses??0} passes</small></span><b>{player.points} FP</b></div>)}</div></section>:null}</>
}
