create type public.draft_status as enum ('waiting','live','paused','complete');
create table public.drafts(id uuid primary key default gen_random_uuid(),league_id uuid not null unique references public.leagues(id) on delete cascade,status public.draft_status not null default 'waiting',rounds smallint not null default 18 check(rounds=18),pick_seconds smallint not null default 60 check(pick_seconds between 15 and 300),current_pick smallint not null default 1,pick_deadline timestamptz,started_at timestamptz,updated_at timestamptz not null default now());
create table public.draft_picks(id bigint generated always as identity primary key,draft_id uuid not null references public.drafts(id) on delete cascade,league_id uuid not null references public.leagues(id) on delete cascade,pick_number smallint not null,round smallint not null check(round between 1 and 18),user_id uuid not null references public.profiles(id),player_id bigint not null references public.players(id),auto_picked boolean not null default false,picked_at timestamptz not null default now(),unique(draft_id,pick_number),unique(league_id,player_id));
create index draft_picks_draft_id_idx on public.draft_picks(draft_id);create index draft_picks_user_id_idx on public.draft_picks(user_id);create index draft_picks_player_id_idx on public.draft_picks(player_id);
alter table public.drafts enable row level security;alter table public.draft_picks enable row level security;grant select on public.drafts,public.draft_picks to authenticated;
create policy "league members read drafts" on public.drafts for select to authenticated using(exists(select 1 from public.league_members m where m.league_id=drafts.league_id and m.user_id=(select auth.uid())));
create policy "league members read picks" on public.draft_picks for select to authenticated using(exists(select 1 from public.league_members m where m.league_id=draft_picks.league_id and m.user_id=(select auth.uid())));

create function public.start_draft(p_league_id uuid,p_pick_seconds smallint default 60) returns uuid language plpgsql security definer set search_path='' as $$declare v_user uuid:=(select auth.uid());v_size int;v_count int;v_id uuid;begin select size into v_size from public.leagues where id=p_league_id and commissioner_id=v_user;if not found then raise exception 'Only the commissioner can start this draft';end if;select count(*) into v_count from public.league_members where league_id=p_league_id;if v_count<>v_size then raise exception 'League must have all % managers before drafting',v_size;end if;insert into public.drafts(league_id,status,pick_seconds,current_pick,pick_deadline,started_at) values(p_league_id,'live',p_pick_seconds,1,now()+make_interval(secs=>p_pick_seconds),now()) on conflict(league_id) do update set status='live',pick_seconds=p_pick_seconds,current_pick=1,pick_deadline=now()+make_interval(secs=>p_pick_seconds),started_at=now(),updated_at=now() returning id into v_id;return v_id;end$$;

create function public.make_draft_pick(p_league_id uuid,p_player_id bigint) returns bigint language plpgsql security definer set search_path='' as $$declare v_user uuid:=(select auth.uid());v_draft public.drafts%rowtype;v_n int;v_round int;v_index int;v_slot int;v_on_clock uuid;v_pick_id bigint;begin select * into v_draft from public.drafts where league_id=p_league_id for update;if not found or v_draft.status<>'live' then raise exception 'Draft is not live';end if;if now()>v_draft.pick_deadline then raise exception 'Pick timer expired';end if;select count(*) into v_n from public.league_members where league_id=p_league_id;v_round=((v_draft.current_pick-1)/v_n)+1;v_index=((v_draft.current_pick-1)%v_n)+1;v_slot=case when mod(v_round,2)=1 then v_index else v_n-v_index+1 end;select user_id into v_on_clock from public.league_members where league_id=p_league_id and draft_slot=v_slot;if v_on_clock<>v_user then raise exception 'It is not your pick';end if;insert into public.draft_picks(draft_id,league_id,pick_number,round,user_id,player_id) values(v_draft.id,p_league_id,v_draft.current_pick,v_round,v_user,p_player_id) returning id into v_pick_id;update public.drafts set current_pick=current_pick+1,status=case when current_pick>=v_n*18 then 'complete'::public.draft_status else status end,pick_deadline=case when current_pick>=v_n*18 then null else now()+make_interval(secs=>pick_seconds) end,updated_at=now() where id=v_draft.id;return v_pick_id;end$$;

create function public.auto_pick_draft(p_league_id uuid) returns bigint language plpgsql security definer set search_path='' as $$declare v_caller uuid:=(select auth.uid());v_draft public.drafts%rowtype;v_n int;v_round int;v_index int;v_slot int;v_user uuid;v_player bigint;v_id bigint;begin if not exists(select 1 from public.league_members where league_id=p_league_id and user_id=v_caller) then raise exception 'League membership required';end if;select * into v_draft from public.drafts where league_id=p_league_id for update;if v_draft.status<>'live' or now()<=v_draft.pick_deadline then raise exception 'Auto-pick is not due';end if;select count(*) into v_n from public.league_members where league_id=p_league_id;v_round=((v_draft.current_pick-1)/v_n)+1;v_index=((v_draft.current_pick-1)%v_n)+1;v_slot=case when mod(v_round,2)=1 then v_index else v_n-v_index+1 end;select user_id into v_user from public.league_members where league_id=p_league_id and draft_slot=v_slot;select p.id into v_player from public.players p where p.active and not exists(select 1 from public.draft_picks dp where dp.league_id=p_league_id and dp.player_id=p.id) order by p.id limit 1;if v_player is null then raise exception 'No players available';end if;insert into public.draft_picks(draft_id,league_id,pick_number,round,user_id,player_id,auto_picked) values(v_draft.id,p_league_id,v_draft.current_pick,v_round,v_user,v_player,true) returning id into v_id;update public.drafts set current_pick=current_pick+1,status=case when current_pick>=v_n*18 then 'complete'::public.draft_status else status end,pick_deadline=case when current_pick>=v_n*18 then null else now()+make_interval(secs=>pick_seconds) end,updated_at=now() where id=v_draft.id;return v_id;end$$;

create function public.draft_order(p_league_id uuid) returns table(draft_slot smallint,user_id uuid,team_name text) language sql security definer set search_path='' stable as $$select m.draft_slot,m.user_id,m.team_name from public.league_members m where m.league_id=p_league_id and exists(select 1 from public.league_members me where me.league_id=p_league_id and me.user_id=(select auth.uid())) order by m.draft_slot$$;
revoke all on function public.start_draft(uuid,smallint),public.make_draft_pick(uuid,bigint),public.auto_pick_draft(uuid),public.draft_order(uuid) from public,anon;grant execute on function public.start_draft(uuid,smallint),public.make_draft_pick(uuid,bigint),public.auto_pick_draft(uuid),public.draft_order(uuid) to authenticated;
alter publication supabase_realtime add table public.drafts,public.draft_picks;

insert into public.players(provider_id,full_name,position,club,competition) values
('seed-haaland','Erling Haaland','FWD','Manchester City','Premier League'),('seed-saka','Bukayo Saka','MID','Arsenal','Premier League'),('seed-salah','Mohamed Salah','FWD','Liverpool','Premier League'),('seed-bellingham','Jude Bellingham','MID','Real Madrid','La Liga'),('seed-yamal','Lamine Yamal','MID','Barcelona','La Liga'),('seed-mbappe','Kylian Mbappé','FWD','Real Madrid','La Liga'),('seed-kane','Harry Kane','FWD','Bayern Munich','Bundesliga'),('seed-wirtz','Florian Wirtz','MID','Bayer Leverkusen','Bundesliga'),('seed-musiala','Jamal Musiala','MID','Bayern Munich','Bundesliga'),('seed-lautaro','Lautaro Martínez','FWD','Inter','Serie A'),('seed-leao','Rafael Leão','MID','Milan','Serie A'),('seed-bastoni','Alessandro Bastoni','DEF','Inter','Serie A'),('seed-dembele','Ousmane Dembélé','FWD','PSG','Ligue 1'),('seed-hakimi','Achraf Hakimi','DEF','PSG','Ligue 1'),('seed-donnarumma','Gianluigi Donnarumma','GK','PSG','Ligue 1') on conflict(provider_id) do nothing;
