-- Generated from ESPN's 2026 top-five-league roster feed by scripts/import-espn-player-pool.mjs.
-- draft_rank is a provisional board: established seed stars first, then curated stars and club/name order.

update public.players
set active = false, draft_rank = null
where provider_id like 'espn:%';

insert into public.players(provider_id,full_name,position,club,competition,active,draft_rank)
values
('espn:252107','Vinícius Júnior','FWD'::public.player_position,'Real Madrid','La Liga',true,16),
('espn:296395','Cole Palmer','MID'::public.player_position,'Chelsea','Premier League',true,17),
('espn:231828','Rodri','MID'::public.player_position,'Manchester City','Premier League',true,18),
('espn:250465','Pedri','MID'::public.player_position,'Barcelona','La Liga',true,19),
('espn:231050','Raphinha','FWD'::public.player_position,'Barcelona','La Liga',true,20),
('espn:235818','Federico Valverde','MID'::public.player_position,'Real Madrid','La Liga',true,21),
('espn:235662','Alexander Isak','FWD'::public.player_position,'Liverpool','Premier League',true,22),
('espn:238262','Declan Rice','MID'::public.player_position,'Arsenal','Premier League',true,23),
('espn:124091','Bruno Fernandes','MID'::public.player_position,'Manchester United','Premier League',true,24),
('espn:250787','Phil Foden','MID'::public.player_position,'Manchester City','Premier League',true,25),
('espn:274745','Khvicha Kvaratskhelia','FWD'::public.player_position,'Paris Saint-Germain','Ligue 1',true,26),
('espn:312146','Nico Williams','FWD'::public.player_position,'Athletic Club','La Liga',true,27),
('espn:227765','Dani Olmo','MID'::public.player_position,'Barcelona','La Liga',true,28),
('espn:203669','Martin Ødegaard','MID'::public.player_position,'Arsenal','Premier League',true,29),
('espn:258906','Viktor Gyökeres','FWD'::public.player_position,'Arsenal','Premier League',true,30),
('espn:355061','João Neves','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,31),
('espn:286831','Michael Olise','MID'::public.player_position,'Bayern Munich','Bundesliga',true,32),
('espn:186381','Serhou Guirassy','FWD'::public.player_position,'Borussia Dortmund','Bundesliga',true,33),
('espn:204441','Nicolò Barella','MID'::public.player_position,'Internazionale','Serie A',true,34),
('espn:217331','Marcus Thuram','FWD'::public.player_position,'Internazionale','Serie A',true,35),
('espn:288897','Vitinha','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,36),
('espn:403234','Vitinha','FWD'::public.player_position,'Genoa','Serie A',true,37),
('espn:328238','Bradley Barcola','FWD'::public.player_position,'Paris Saint-Germain','Ligue 1',true,38),
('espn:277385','William Saliba','DEF'::public.player_position,'Arsenal','Premier League',true,39),
('espn:236322','Gabriel Magalhães','DEF'::public.player_position,'Arsenal','Premier League',true,40),
('espn:157892','Virgil van Dijk','DEF'::public.player_position,'Liverpool','Premier League',true,41),
('espn:223532','Trent Alexander-Arnold','DEF'::public.player_position,'Real Madrid','La Liga',true,42),
('espn:236721','Alphonso Davies','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,43),
('espn:290591','Nuno Mendes','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,44),
('espn:159047','Marquinhos','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,45),
('espn:169438','Antonio Rüdiger','DEF'::public.player_position,'Real Madrid','La Liga',true,46),
('espn:368992','Pau Cubarsí','DEF'::public.player_position,'Barcelona','La Liga',true,47),
('espn:3118049','Aimar García Díez','DEF'::public.player_position,'Real Madrid','La Liga',true,48),
('espn:3117407','Alexis Ciria','FWD'::public.player_position,'Real Madrid','La Liga',true,49),
('espn:310637','Álvaro Carreras','DEF'::public.player_position,'Real Madrid','La Liga',true,50),
('espn:257237','Andriy Lunin','GK'::public.player_position,'Real Madrid','La Liga',true,51),
('espn:310452','Arda Güler','MID'::public.player_position,'Real Madrid','La Liga',true,52),
('espn:265919','Aurélien Tchouaméni','MID'::public.player_position,'Real Madrid','La Liga',true,53),
('espn:199833','Bernardo Silva','MID'::public.player_position,'Real Madrid','La Liga',true,54),
('espn:246532','Brahim Díaz','MID'::public.player_position,'Real Madrid','La Liga',true,55),
('espn:380286','Carlos Espí','FWD'::public.player_position,'Real Madrid','La Liga',true,56),
('espn:376422','Daniel Yañez','FWD'::public.player_position,'Real Madrid','La Liga',true,57),
('espn:356000','Dean Huijsen','DEF'::public.player_position,'Real Madrid','La Liga',true,58),
('espn:213248','Denzel Dumfries','DEF'::public.player_position,'Real Madrid','La Liga',true,59),
('espn:3117399','Diego Lacosta','MID'::public.player_position,'Real Madrid','La Liga',true,60),
('espn:228402','Éder Militão','DEF'::public.player_position,'Real Madrid','La Liga',true,61),
('espn:285150','Eduardo Camavinga','MID'::public.player_position,'Real Madrid','La Liga',true,62),
('espn:346612','Endrick','FWD'::public.player_position,'Real Madrid','La Liga',true,63),
('espn:217475','Ferland Mendy','DEF'::public.player_position,'Real Madrid','La Liga',true,64),
('espn:251634','Ibrahima Konaté','DEF'::public.player_position,'Real Madrid','La Liga',true,65),
('espn:3117410','Jacobo Ortega Conde','FWD'::public.player_position,'Real Madrid','La Liga',true,66),
('espn:84349','Javier Navarro','GK'::public.player_position,'Real Madrid','La Liga',true,67),
('espn:405544','Jesús Fortea','DEF'::public.player_position,'Real Madrid','La Liga',true,68),
('espn:388339','Joan Martínez','DEF'::public.player_position,'Real Madrid','La Liga',true,69),
('espn:415478','Jorge Cestero','MID'::public.player_position,'Real Madrid','La Liga',true,70),
('espn:419888','Lamini Fati','DEF'::public.player_position,'Real Madrid','La Liga',true,71),
('espn:259910','Marc Cucurella','DEF'::public.player_position,'Real Madrid','La Liga',true,72),
('espn:330352','Mario Rivas','DEF'::public.player_position,'Real Madrid','La Liga',true,73),
('espn:388338','Raúl Asencio','DEF'::public.player_position,'Real Madrid','La Liga',true,74),
('espn:267804','Rodrygo','FWD'::public.player_position,'Real Madrid','La Liga',true,75),
('espn:350351','Sergio Mestre','GK'::public.player_position,'Real Madrid','La Liga',true,76),
('espn:134283','Thibaut Courtois','GK'::public.player_position,'Real Madrid','La Liga',true,77),
('espn:402479','Yan Diomande','FWD'::public.player_position,'Real Madrid','La Liga',true,78),
('espn:323703','Alejandro Balde','DEF'::public.player_position,'Barcelona','La Liga',true,79),
('espn:3116262','Alex González Yanes','FWD'::public.player_position,'Barcelona','La Liga',true,80),
('espn:300377','Álvaro Cortés','DEF'::public.player_position,'Barcelona','La Liga',true,81),
('espn:186430','Andreas Christensen','DEF'::public.player_position,'Barcelona','La Liga',true,82),
('espn:268782','Anthony Gordon','FWD'::public.player_position,'Barcelona','La Liga',true,83),
('espn:377529','Áron Yaakobishvili','GK'::public.player_position,'Barcelona','La Liga',true,84),
('espn:403575','Brian Fariñas','MID'::public.player_position,'Barcelona','La Liga',true,85),
('espn:416502','Ebrima Tunkara','MID'::public.player_position,'Barcelona','La Liga',true,86),
('espn:128714','Eric García','DEF'::public.player_position,'Barcelona','La Liga',true,87),
('espn:354334','Fermín López','MID'::public.player_position,'Barcelona','La Liga',true,88),
('espn:265869','Ferran Torres','FWD'::public.player_position,'Barcelona','La Liga',true,89),
('espn:219022','Frenkie de Jong','MID'::public.player_position,'Barcelona','La Liga',true,90),
('espn:323702','Gavi','MID'::public.player_position,'Barcelona','La Liga',true,91),
('espn:312015','Gerard Martín','DEF'::public.player_position,'Barcelona','La Liga',true,92),
('espn:388286','Guille Fernández','MID'::public.player_position,'Barcelona','La Liga',true,93),
('espn:399200','Hamza Abdelkarim','FWD'::public.player_position,'Barcelona','La Liga',true,94),
('espn:363039','Héctor Fort','DEF'::public.player_position,'Barcelona','La Liga',true,95),
('espn:276128','Ibrahim Diarra','FWD'::public.player_position,'Barcelona','La Liga',true,96),
('espn:403576','Iker Rodríguez','GK'::public.player_position,'Barcelona','La Liga',true,97),
('espn:365318','Jesse Bisiwu','MID'::public.player_position,'Barcelona','La Liga',true,98),
('espn:297362','Joan García','GK'::public.player_position,'Barcelona','La Liga',true,99),
('espn:403588','Jofre Torrents','DEF'::public.player_position,'Barcelona','La Liga',true,100),
('espn:416511','Jordi Pesquer','DEF'::public.player_position,'Barcelona','La Liga',true,101),
('espn:231692','Jules Koundé','DEF'::public.player_position,'Barcelona','La Liga',true,102),
('espn:274913','Karim Adeyemi','FWD'::public.player_position,'Barcelona','La Liga',true,103),
('espn:376423','Marc Bernal','MID'::public.player_position,'Barcelona','La Liga',true,104),
('espn:345489','Marc Casadó','MID'::public.player_position,'Barcelona','La Liga',true,105),
('espn:416496','Orian Goren','MID'::public.player_position,'Barcelona','La Liga',true,106),
('espn:403585','Òscar Gistau','FWD'::public.player_position,'Barcelona','La Liga',true,107),
('espn:331152','Roony Bardghji','FWD'::public.player_position,'Barcelona','La Liga',true,108),
('espn:403580','Shane Kluivert','FWD'::public.player_position,'Barcelona','La Liga',true,109),
('espn:403590','Tomás Marqués','MID'::public.player_position,'Barcelona','La Liga',true,110),
('espn:388285','Toni Fernández','FWD'::public.player_position,'Barcelona','La Liga',true,111),
('espn:131634','Wojciech Szczesny','GK'::public.player_position,'Barcelona','La Liga',true,112),
('espn:403582','Xavi Espart','DEF'::public.player_position,'Barcelona','La Liga',true,113),
('espn:362211','Abdukodir Khusanov','DEF'::public.player_position,'Manchester City','Premier League',true,114),
('espn:273292','Antoine Semenyo','FWD'::public.player_position,'Manchester City','Premier League',true,115),
('espn:361355','Claudio Echeverri','MID'::public.player_position,'Manchester City','Premier League',true,116),
('espn:238472','Elliot Anderson','MID'::public.player_position,'Manchester City','Premier League',true,117),
('espn:167192','Gerónimo Rulli','GK'::public.player_position,'Manchester City','Premier League',true,118),
('espn:172850','Jack Grealish','MID'::public.player_position,'Manchester City','Premier League',true,119),
('espn:283672','Jérémy Doku','FWD'::public.player_position,'Manchester City','Premier League',true,120),
('espn:389329','Jeremy Monga','FWD'::public.player_position,'Manchester City','Premier League',true,121),
('espn:307117','Josh Wilson-Esbrand','DEF'::public.player_position,'Manchester City','Premier League',true,122),
('espn:299910','Josko Gvardiol','DEF'::public.player_position,'Manchester City','Premier League',true,123),
('espn:265907','Marc Guéhi','DEF'::public.player_position,'Manchester City','Premier League',true,124),
('espn:177545','Marcus Bettinelli','GK'::public.player_position,'Manchester City','Premier League',true,125),
('espn:154595','Mateo Kovacic','MID'::public.player_position,'Manchester City','Premier League',true,126),
('espn:303785','Matheus Nunes','MID'::public.player_position,'Manchester City','Premier League',true,127),
('espn:347046','Max Alleyne','DEF'::public.player_position,'Manchester City','Premier League',true,128),
('espn:323986','Nico González','MID'::public.player_position,'Manchester City','Premier League',true,129),
('espn:328464','Nico O''Reilly','DEF'::public.player_position,'Manchester City','Premier League',true,130),
('espn:303745','Omar Marmoush','FWD'::public.player_position,'Manchester City','Premier League',true,131),
('espn:272512','Rayan Aït-Nouri','DEF'::public.player_position,'Manchester City','Premier League',true,132),
('espn:298008','Rayan Cherki','MID'::public.player_position,'Manchester City','Premier League',true,133),
('espn:325564','Rico Lewis','DEF'::public.player_position,'Manchester City','Premier League',true,134),
('espn:234878','Rúben Dias','DEF'::public.player_position,'Manchester City','Premier League',true,135),
('espn:304470','Savinho','FWD'::public.player_position,'Manchester City','Premier League',true,136),
('espn:261328','Tijjani Reijnders','MID'::public.player_position,'Manchester City','Premier League',true,137),
('espn:361434','Vitor Reis','DEF'::public.player_position,'Manchester City','Premier League',true,138),
('espn:249299','Alexis Mac Allister','MID'::public.player_position,'Liverpool','Premier League',true,139),
('espn:196876','Alisson Becker','GK'::public.player_position,'Liverpool','Premier League',true,140),
('espn:359218','Calum Scanlon','DEF'::public.player_position,'Liverpool','Premier League',true,141),
('espn:291353','Calvin Ramsay','DEF'::public.player_position,'Liverpool','Premier League',true,142),
('espn:249524','Cody Gakpo','FWD'::public.player_position,'Liverpool','Premier League',true,143),
('espn:250183','Conor Bradley','DEF'::public.player_position,'Liverpool','Premier League',true,144),
('espn:190257','Curtis Jones','MID'::public.player_position,'Liverpool','Premier League',true,145),
('espn:257206','Dominik Szoboszlai','MID'::public.player_position,'Liverpool','Premier League',true,146),
('espn:234306','Federico Chiesa','FWD'::public.player_position,'Liverpool','Premier League',true,147),
('espn:194121','Freddie Woodman','GK'::public.player_position,'Liverpool','Premier League',true,148),
('espn:274742','Giorgi Mamardashvili','GK'::public.player_position,'Liverpool','Premier League',true,149),
('espn:380082','Giovanni Leoni','DEF'::public.player_position,'Liverpool','Premier League',true,150),
('espn:315879','Harvey Davies','GK'::public.player_position,'Liverpool','Premier League',true,151),
('espn:280806','Harvey Elliott','MID'::public.player_position,'Liverpool','Premier League',true,152),
('espn:304901','Hugo Ekitike','FWD'::public.player_position,'Liverpool','Premier League',true,153),
('espn:407397','Ifeanyi Ndukwe','DEF'::public.player_position,'Liverpool','Premier League',true,154),
('espn:326230','James McConnell','MID'::public.player_position,'Liverpool','Premier League',true,155),
('espn:281119','Jeremie Frimpong','DEF'::public.player_position,'Liverpool','Premier League',true,156),
('espn:355980','Jérémy Jacquet','DEF'::public.player_position,'Liverpool','Premier League',true,157),
('espn:102053','Joe Gomez','DEF'::public.player_position,'Liverpool','Premier League',true,158),
('espn:3111014','Joshua Abe','FWD'::public.player_position,'Liverpool','Premier League',true,159),
('espn:395890','Joshua Lambie','FWD'::public.player_position,'Liverpool','Premier League',true,160),
('espn:357162','Kieran Morrison','MID'::public.player_position,'Liverpool','Premier League',true,161),
('espn:226177','Kostas Tsimikas','DEF'::public.player_position,'Liverpool','Premier League',true,162),
('espn:350661','Lewis Koumas','FWD'::public.player_position,'Liverpool','Premier League',true,163),
('espn:32572','Luke Chambers','DEF'::public.player_position,'Liverpool','Premier League',true,164),
('espn:323110','Milos Kerkez','DEF'::public.player_position,'Liverpool','Premier League',true,165),
('espn:379588','Rio Ngumoha','FWD'::public.player_position,'Liverpool','Premier League',true,166),
('espn:270821','Ronald Araújo','DEF'::public.player_position,'Liverpool','Premier League',true,167),
('espn:274632','Ryan Gravenberch','MID'::public.player_position,'Liverpool','Premier League',true,168),
('espn:330605','Stefan Bajcetic','MID'::public.player_position,'Liverpool','Premier League',true,169),
('espn:414255','Talla Ndiaye','DEF'::public.player_position,'Liverpool','Premier League',true,170),
('espn:356075','Trey Nyoni','MID'::public.player_position,'Liverpool','Premier League',true,171),
('espn:397545','Víctor Muñoz','FWD'::public.player_position,'Liverpool','Premier League',true,172),
('espn:289840','Vitezslav Jaros','GK'::public.player_position,'Liverpool','Premier League',true,173),
('espn:152479','Wataru Endo','MID'::public.player_position,'Liverpool','Premier League',true,174),
('espn:395778','Will Wright','FWD'::public.player_position,'Liverpool','Premier League',true,175),
('espn:241077','Ben White','DEF'::public.player_position,'Arsenal','Premier League',true,176),
('espn:218522','Bruno Guimarães','MID'::public.player_position,'Arsenal','Premier League',true,177),
('espn:303793','Christos Tzolis','FWD'::public.player_position,'Arsenal','Premier League',true,178),
('espn:328497','Cristhian Mosquera','DEF'::public.player_position,'Arsenal','Premier League',true,179),
('espn:196176','David Raya','GK'::public.player_position,'Arsenal','Premier League',true,180),
('espn:251400','Eberechi Eze','MID'::public.player_position,'Arsenal','Premier League',true,181),
('espn:349733','Ethan Nwaneri','MID'::public.player_position,'Arsenal','Premier League',true,182),
('espn:88865','Fabio Vieira','MID'::public.player_position,'Arsenal','Premier League',true,183),
('espn:217289','Gabriel Jesus','FWD'::public.player_position,'Arsenal','Premier League',true,184),
('espn:269844','Gabriel Martinelli','FWD'::public.player_position,'Arsenal','Premier League',true,185),
('espn:265921','Illan Meslier','GK'::public.player_position,'Arsenal','Premier League',true,186),
('espn:282716','Jurriën Timber','DEF'::public.player_position,'Arsenal','Premier League',true,187),
('espn:231182','Kai Havertz','FWD'::public.player_position,'Arsenal','Premier League',true,188),
('espn:169532','Kepa Arrizabalaga','GK'::public.player_position,'Arsenal','Premier League',true,189),
('espn:287266','Martín Zubimendi','MID'::public.player_position,'Arsenal','Premier League',true,190),
('espn:209581','Mikel Merino','MID'::public.player_position,'Arsenal','Premier League',true,191),
('espn:352758','Myles Lewis-Skelly','DEF'::public.player_position,'Arsenal','Premier League',true,192),
('espn:293236','Noni Madueke','FWD'::public.player_position,'Arsenal','Premier League',true,193),
('espn:292062','Piero Hincapié','DEF'::public.player_position,'Arsenal','Premier League',true,194),
('espn:227794','Reiss Nelson','FWD'::public.player_position,'Arsenal','Premier League',true,195),
('espn:298329','Riccardo Calafiori','DEF'::public.player_position,'Arsenal','Premier League',true,196),
('espn:343573','Tommy Setford','GK'::public.player_position,'Arsenal','Premier League',true,197),
('espn:410638','Adam El-Chaar','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,198),
('espn:359370','Aleksandar Pavlovic','MID'::public.player_position,'Bayern Munich','Bundesliga',true,199),
('espn:333400','Arijon Ibrahimovic','MID'::public.player_position,'Bayern Munich','Bundesliga',true,200),
('espn:409016','Bara Sapoko Ndiaye','MID'::public.player_position,'Bayern Munich','Bundesliga',true,201),
('espn:422013','Bastian Assomo','FWD'::public.player_position,'Bayern Munich','Bundesliga',true,202),
('espn:311571','Bryan Zaragoza','FWD'::public.player_position,'Bayern Munich','Bundesliga',true,203),
('espn:3110056','David Podar-Stiube','GK'::public.player_position,'Bayern Munich','Bundesliga',true,204),
('espn:222793','Dayot Upamecano','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,205),
('espn:408344','Felipe Chávez','MID'::public.player_position,'Bayern Munich','Bundesliga',true,206),
('espn:420811','Filip Pavic','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,207),
('espn:379223','Guido Rovere','MID'::public.player_position,'Bayern Munich','Bundesliga',true,208),
('espn:97111','Hiroki Ito','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,209),
('espn:304572','Ismael Saibari','MID'::public.player_position,'Bayern Munich','Bundesliga',true,210),
('espn:224144','João Palhinha','MID'::public.player_position,'Bayern Munich','Bundesliga',true,211),
('espn:323790','Jonas Urbig','GK'::public.player_position,'Bayern Munich','Bundesliga',true,212),
('espn:188052','Jonathan Tah','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,213),
('espn:190161','Joshua Kimmich','MID'::public.player_position,'Bayern Munich','Bundesliga',true,214),
('espn:276329','Josip Stanisic','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,215),
('espn:157688','Kim Min-Jae','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,216),
('espn:169189','Konrad Laimer','MID'::public.player_position,'Bayern Munich','Bundesliga',true,217),
('espn:402841','Lennart Karl','MID'::public.player_position,'Bayern Munich','Bundesliga',true,218),
('espn:388141','Leon Klanac','GK'::public.player_position,'Bayern Munich','Bundesliga',true,219),
('espn:257390','Luis Díaz','FWD'::public.player_position,'Bayern Munich','Bundesliga',true,220),
('espn:84774','Manuel Neuer','GK'::public.player_position,'Bayern Munich','Bundesliga',true,221),
('espn:417373','Maycon Cardozo','MID'::public.player_position,'Bayern Munich','Bundesliga',true,222),
('espn:3110058','Michael Matošević','MID'::public.player_position,'Bayern Munich','Bundesliga',true,223),
('espn:120829','Nathaniel Brown','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,224),
('espn:3104227','Oluwaseyi Wilson','FWD'::public.player_position,'Bayern Munich','Bundesliga',true,225),
('espn:403935','Raphael Pavlic','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,226),
('espn:3110059','Richard Ajayi Oluwaseyi','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,227),
('espn:403803','Roko Mijatovic','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,228),
('espn:287225','Sacha Boey','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,229),
('espn:178980','Serge Gnabry','FWD'::public.player_position,'Bayern Munich','Bundesliga',true,230),
('espn:3104162','Simon Schaff','MID'::public.player_position,'Bayern Munich','Bundesliga',true,231),
('espn:3110057','Skender Nuraj','FWD'::public.player_position,'Bayern Munich','Bundesliga',true,232),
('espn:113733','Sven Ulreich','GK'::public.player_position,'Bayern Munich','Bundesliga',true,233),
('espn:3104151','Tim Binder','MID'::public.player_position,'Bayern Munich','Bundesliga',true,234),
('espn:324660','Tom Bischof','MID'::public.player_position,'Bayern Munich','Bundesliga',true,235),
('espn:388224','Vincent Manuba','DEF'::public.player_position,'Bayern Munich','Bundesliga',true,236),
('espn:387725','Alessandro Longoni','GK'::public.player_position,'Paris Saint-Germain','Ligue 1',true,237),
('espn:336388','Désiré Doué','FWD'::public.player_position,'Paris Saint-Germain','Ligue 1',true,238),
('espn:403578','Dro Fernández','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,239),
('espn:214596','Fabián Ruiz','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,240),
('espn:388522','Ibrahim Mbaye','FWD'::public.player_position,'Paris Saint-Germain','Ligue 1',true,241),
('espn:304503','Illia Zabarnyi','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,242),
('espn:316128','Lucas Beraldo','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,243),
('espn:288925','Lucas Chevalier','GK'::public.player_position,'Paris Saint-Germain','Ligue 1',true,244),
('espn:160115','Lucas Digne','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,245),
('espn:196200','Lucas Hernández','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,246),
('espn:329690','Maghnes Akliouche','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,247),
('espn:248699','Matvei Safonov','GK'::public.player_position,'Paris Saint-Germain','Ligue 1',true,248),
('espn:403419','Quentin Ndjantou','FWD'::public.player_position,'Paris Saint-Germain','Ligue 1',true,249),
('espn:379088','Senny Mayulu','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,250),
('espn:345581','Warren Zaïre-Emery','MID'::public.player_position,'Paris Saint-Germain','Ligue 1',true,251),
('espn:287005','Willian Pacho','DEF'::public.player_position,'Paris Saint-Germain','Ligue 1',true,252),
('espn:363218','Aaron Anselmino','DEF'::public.player_position,'Chelsea','Premier League',true,253),
('espn:231718','Axel Disasi','DEF'::public.player_position,'Chelsea','Premier League',true,254),
('espn:282585','Benoît Badiashile','DEF'::public.player_position,'Chelsea','Premier League',true,255),
('espn:399896','Calvin Diakite','DEF'::public.player_position,'Chelsea','Premier League',true,256),
('espn:115271','Danny Welbeck','FWD'::public.player_position,'Chelsea','Premier League',true,257),
('espn:316560','Dário Essugo','MID'::public.player_position,'Chelsea','Premier League',true,258),
('espn:402242','Dastan Satpaev','FWD'::public.player_position,'Chelsea','Premier League',true,259),
('espn:301047','David Datro Fofana','FWD'::public.player_position,'Chelsea','Premier League',true,260),
('espn:304871','Emmanuel Emegha','FWD'::public.player_position,'Chelsea','Premier League',true,261),
('espn:285450','Enzo Fernández','MID'::public.player_position,'Chelsea','Premier League',true,262),
('espn:376481','Estêvão','FWD'::public.player_position,'Chelsea','Premier League',true,263),
('espn:286774','Gaga Slonina','GK'::public.player_position,'Chelsea','Premier League',true,264),
('espn:376274','Geovany Quenda','MID'::public.player_position,'Chelsea','Premier League',true,265),
('espn:339879','Jamie Gittens','FWD'::public.player_position,'Chelsea','Premier League',true,266),
('espn:284960','João Pedro','FWD'::public.player_position,'Chelsea','Premier League',true,267),
('espn:127262','Jordan Henderson','MID'::public.player_position,'Chelsea','Premier League',true,268),
('espn:353951','Jorrel Hato','DEF'::public.player_position,'Chelsea','Premier League',true,269),
('espn:368317','Josh Acheampong','DEF'::public.player_position,'Chelsea','Premier League',true,270),
('espn:379702','Landon Emenalo','DEF'::public.player_position,'Chelsea','Premier League',true,271),
('espn:296410','Levi Colwill','DEF'::public.player_position,'Chelsea','Premier League',true,272),
('espn:307114','Liam Delap','FWD'::public.player_position,'Chelsea','Premier League',true,273),
('espn:399562','Mahdi Nicoll-Jazuli','MID'::public.player_position,'Chelsea','Premier League',true,274),
('espn:308947','Malo Gusto','DEF'::public.player_position,'Chelsea','Premier League',true,275),
('espn:355433','Mamadou Sarr','DEF'::public.player_position,'Chelsea','Premier League',true,276),
('espn:363038','Marc Guiu','FWD'::public.player_position,'Chelsea','Premier League',true,277),
('espn:362486','Marco Palestra','DEF'::public.player_position,'Chelsea','Premier League',true,278),
('espn:265918','Maxence Lacroix','DEF'::public.player_position,'Chelsea','Premier League',true,279),
('espn:332343','Mike Penders','GK'::public.player_position,'Chelsea','Premier League',true,280),
('espn:289877','Moisés Caicedo','MID'::public.player_position,'Chelsea','Premier League',true,281),
('espn:265653','Morgan Rogers','MID'::public.player_position,'Chelsea','Premier League',true,282),
('espn:299911','Mykhailo Mudryk','MID'::public.player_position,'Chelsea','Premier League',true,283),
('espn:308524','Nicolas Jackson','FWD'::public.player_position,'Chelsea','Premier League',true,284),
('espn:408508','Olutayo Subuloye','DEF'::public.player_position,'Chelsea','Premier League',true,285),
('espn:331082','Omari Kellyman','MID'::public.player_position,'Chelsea','Premier League',true,286),
('espn:256115','Pedro Neto','FWD'::public.player_position,'Chelsea','Premier League',true,287),
('espn:300331','Pep Chavarría','DEF'::public.player_position,'Chelsea','Premier League',true,288),
('espn:189007','Reece James','DEF'::public.player_position,'Chelsea','Premier League',true,289),
('espn:400749','Reggie Walsh','MID'::public.player_position,'Chelsea','Premier League',true,290),
('espn:399564','Reggie Watson','MID'::public.player_position,'Chelsea','Premier League',true,291),
('espn:108662','Robert Sánchez','GK'::public.player_position,'Chelsea','Premier League',true,292),
('espn:308217','Romeo Lavia','MID'::public.player_position,'Chelsea','Premier League',true,293),
('espn:399895','Ryan Kavuma-Mcqueen','FWD'::public.player_position,'Chelsea','Premier League',true,294),
('espn:349214','Ted Curd','GK'::public.player_position,'Chelsea','Premier League',true,295),
('espn:300049','Teddy Sharman-Lowe','GK'::public.player_position,'Chelsea','Premier League',true,296),
('espn:231198','Tosin Adarabioyo','DEF'::public.player_position,'Chelsea','Premier League',true,297),
('espn:320760','Valentín Barco','MID'::public.player_position,'Chelsea','Premier League',true,298),
('espn:270190','Wesley Fofana','DEF'::public.player_position,'Chelsea','Premier League',true,299),
('espn:291630','Amad Diallo','FWD'::public.player_position,'Manchester United','Premier League',true,300),
('espn:314858','Andrey Santos','MID'::public.player_position,'Manchester United','Premier League',true,301),
('espn:356044','Ayden Heaven','DEF'::public.player_position,'Manchester United','Premier League',true,302),
('espn:289155','Benjamin Sesko','FWD'::public.player_position,'Manchester United','Premier League',true,303),
('espn:271170','Bryan Mbeumo','FWD'::public.player_position,'Manchester United','Premier League',true,304),
('espn:381055','Daniel Armer','DEF'::public.player_position,'Manchester United','Premier League',true,305),
('espn:347049','Daniel Gore','MID'::public.player_position,'Manchester United','Premier League',true,306),
('espn:325550','Dermot Mee','GK'::public.player_position,'Manchester United','Premier League',true,307),
('espn:387634','Diego León','DEF'::public.player_position,'Manchester United','Premier League',true,308),
('espn:238902','Diogo Dalot','DEF'::public.player_position,'Manchester United','Premier League',true,309),
('espn:398006','Enzo Kana-Biyik','FWD'::public.player_position,'Manchester United','Premier League',true,310),
('espn:368547','Ethan Wheatley','FWD'::public.player_position,'Manchester United','Premier League',true,311),
('espn:410992','Fred Heath','GK'::public.player_position,'Manchester United','Premier League',true,312),
('espn:356940','Harry Amass','DEF'::public.player_position,'Manchester United','Premier League',true,313),
('espn:157073','Harry Maguire','DEF'::public.player_position,'Manchester United','Premier League',true,314),
('espn:205081','Jack Fletcher','MID'::public.player_position,'Manchester United','Premier League',true,315),
('espn:384068','Jacob Devaney','MID'::public.player_position,'Manchester United','Premier League',true,316),
('espn:386199','Jaydan Kamason','DEF'::public.player_position,'Manchester United','Premier League',true,317),
('espn:381057','Jim Thwaites','MID'::public.player_position,'Manchester United','Premier League',true,318),
('espn:3108507','JJ Gabriel','FWD'::public.player_position,'Manchester United','Premier League',true,319),
('espn:276327','Joshua Zirkzee','FWD'::public.player_position,'Manchester United','Premier League',true,320),
('espn:130877','Karl Darlow','GK'::public.player_position,'Manchester United','Premier League',true,321),
('espn:328466','Kobbie Mainoo','MID'::public.player_position,'Manchester United','Premier League',true,322),
('espn:340206','Leny Yoro','DEF'::public.player_position,'Manchester United','Premier League',true,323),
('espn:233937','Lisandro Martínez','DEF'::public.player_position,'Manchester United','Premier League',true,324),
('espn:167127','Luke Shaw','DEF'::public.player_position,'Manchester United','Premier League',true,325),
('espn:241468','Manuel Ugarte','MID'::public.player_position,'Manchester United','Premier League',true,326),
('espn:230945','Marcus Rashford','FWD'::public.player_position,'Manchester United','Premier League',true,327),
('espn:231167','Mason Mount','MID'::public.player_position,'Manchester United','Premier League',true,328),
('espn:259902','Matheus Cunha','FWD'::public.player_position,'Manchester United','Premier League',true,329),
('espn:239349','Matthijs de Ligt','DEF'::public.player_position,'Manchester United','Premier League',true,330),
('espn:239350','Noussair Mazraoui','DEF'::public.player_position,'Manchester United','Premier League',true,331),
('espn:366781','Patrick Dorgu','DEF'::public.player_position,'Manchester United','Premier League',true,332),
('espn:301425','Senne Lammens','GK'::public.player_position,'Manchester United','Premier League',true,333),
('espn:358180','Shea Lacey','FWD'::public.player_position,'Manchester United','Premier League',true,334),
('espn:419387','Solomon Honor','GK'::public.player_position,'Manchester United','Premier League',true,335),
('espn:308778','Toby Collyer','MID'::public.player_position,'Manchester United','Premier League',true,336),
('espn:42250','Tom Heaton','GK'::public.player_position,'Manchester United','Premier League',true,337),
('espn:393138','Tyler Fletcher','MID'::public.player_position,'Manchester United','Premier League',true,338),
('espn:397881','Tynan Thompson','FWD'::public.player_position,'Manchester United','Premier League',true,339),
('espn:193297','Youri Tielemans','MID'::public.player_position,'Manchester United','Premier League',true,340),
('espn:229645','Ademola Lookman','FWD'::public.player_position,'Atlético Madrid','La Liga',true,341),
('espn:166396','Alejandro Grimaldo','DEF'::public.player_position,'Atlético Madrid','La Liga',true,342),
('espn:386898','Aleksa Puric','DEF'::public.player_position,'Atlético Madrid','La Liga',true,343),
('espn:297373','Álex Baena','MID'::public.player_position,'Atlético Madrid','La Liga',true,344),
('espn:188230','Alexander Sørloth','FWD'::public.player_position,'Atlético Madrid','La Liga',true,345),
('espn:328289','Arnau Ortiz','FWD'::public.player_position,'Atlético Madrid','La Liga',true,346),
('espn:345110','Arnau Solà','DEF'::public.player_position,'Atlético Madrid','La Liga',true,347),
('espn:324192','Carlos Martín','FWD'::public.player_position,'Atlético Madrid','La Liga',true,348),
('espn:388084','Dani Rubio','GK'::public.player_position,'Atlético Madrid','La Liga',true,349),
('espn:368593','Daniel Martinez','DEF'::public.player_position,'Atlético Madrid','La Liga',true,350),
('espn:257786','Dávid Hancko','DEF'::public.player_position,'Atlético Madrid','La Liga',true,351),
('espn:323838','Giuliano Simeone','FWD'::public.player_position,'Atlético Madrid','La Liga',true,352),
('espn:417258','Iker Luque','FWD'::public.player_position,'Atlético Madrid','La Liga',true,353),
('espn:149622','Jan Oblak','GK'::public.player_position,'Atlético Madrid','La Liga',true,354),
('espn:373877','Javier Boñar','DEF'::public.player_position,'Atlético Madrid','La Liga',true,355),
('espn:290802','Johnny Cardoso','MID'::public.player_position,'Atlético Madrid','La Liga',true,356),
('espn:184757','Jorge Castillo','MID'::public.player_position,'Atlético Madrid','La Liga',true,357),
('espn:354378','Jorge Domínguez','DEF'::public.player_position,'Atlético Madrid','La Liga',true,358),
('espn:188398','José María Giménez','DEF'::public.player_position,'Atlético Madrid','La Liga',true,359),
('espn:277206','Julián Álvarez','FWD'::public.player_position,'Atlético Madrid','La Liga',true,360),
('espn:140791','Koke','MID'::public.player_position,'Atlético Madrid','La Liga',true,361),
('espn:274197','Lee Kang-In','MID'::public.player_position,'Atlético Madrid','La Liga',true,362),
('espn:332613','Marc Pubill','DEF'::public.player_position,'Atlético Madrid','La Liga',true,363),
('espn:206474','Marcos Llorente','MID'::public.player_position,'Atlético Madrid','La Liga',true,364),
('espn:297229','Matteo Ruggeri','DEF'::public.player_position,'Atlético Madrid','La Liga',true,365),
('espn:421996','Miguel Cubo','FWD'::public.player_position,'Atlético Madrid','La Liga',true,366),
('espn:274911','Morten Hjulmand','MID'::public.player_position,'Atlético Madrid','La Liga',true,367),
('espn:164826','Nahuel Molina','DEF'::public.player_position,'Atlético Madrid','La Liga',true,368),
('espn:318554','Obed Vargas','MID'::public.player_position,'Atlético Madrid','La Liga',true,369),
('espn:336634','Pablo Barrios','MID'::public.player_position,'Atlético Madrid','La Liga',true,370),
('espn:74630','Rodrigo Mendoza','MID'::public.player_position,'Atlético Madrid','La Liga',true,371),
('espn:417403','Sergio Esteban','FWD'::public.player_position,'Atlético Madrid','La Liga',true,372),
('espn:190291','Thomas Lemar','MID'::public.player_position,'Atlético Madrid','La Liga',true,373),
('espn:291629','Fábio Silva','FWD'::public.player_position,'Borussia Dortmund','Bundesliga',true,374),
('espn:403781','Mathis Albert','FWD'::public.player_position,'Borussia Dortmund','Bundesliga',true,375),
('espn:290639','Maximilian Beier','FWD'::public.player_position,'Borussia Dortmund','Bundesliga',true,376),
('espn:403833','Samuele Inácio','FWD'::public.player_position,'Borussia Dortmund','Bundesliga',true,377),
('espn:179359','Arkadiusz Milik','FWD'::public.player_position,'Juventus','Serie A',true,378),
('espn:3102531','Arman Durmiši','FWD'::public.player_position,'Juventus','Serie A',true,379),
('espn:404034','Destiny Elimoghale','FWD'::public.player_position,'Juventus','Serie A',true,380),
('espn:260300','Edon Zhegrova','FWD'::public.player_position,'Juventus','Serie A',true,381),
('espn:312659','Francisco Conceição','FWD'::public.player_position,'Juventus','Serie A',true,382),
('espn:388606','Jeff Ekhator','FWD'::public.player_position,'Juventus','Serie A',true,383),
('espn:206153','Jérémie Boga','FWD'::public.player_position,'Juventus','Serie A',true,384),
('espn:273499','Jonathan David','FWD'::public.player_position,'Juventus','Serie A',true,385),
('espn:349101','Justin Oboavwoduo','FWD'::public.player_position,'Juventus','Serie A',true,386),
('espn:366509','Kenan Yildiz','FWD'::public.player_position,'Juventus','Serie A',true,387),
('espn:391034','Kerim Alajbegovic','FWD'::public.player_position,'Juventus','Serie A',true,388),
('espn:76017','Nico González','FWD'::public.player_position,'Juventus','Serie A',true,389),
('espn:252971','Randal Kolo Muani','FWD'::public.player_position,'Juventus','Serie A',true,390),
('espn:271132','Alexis Saelemaekers','FWD'::public.player_position,'AC Milan','Serie A',true,391),
('espn:382572','Andrej Kostic','FWD'::public.player_position,'AC Milan','Serie A',true,392),
('espn:420158','Aurelien Gurnier','FWD'::public.player_position,'AC Milan','Serie A',true,393),
('espn:222176','Christopher Nkunku','FWD'::public.player_position,'AC Milan','Serie A',true,394),
('espn:414987','Emanuele Borsani','FWD'::public.player_position,'AC Milan','Serie A',true,395)
on conflict(provider_id) do update
set full_name = excluded.full_name,
    position = excluded.position,
    club = excluded.club,
    competition = excluded.competition,
    active = true,
    draft_rank = excluded.draft_rank;
